# Minimal local stub for the (untyped) ``networkx`` package. Only the surface
# the dynamic-model graph helpers use is typed: a node-generic DiGraph,
# find_cycle (raises NetworkXNoCycle), and topological_sort. This lets the
# helpers avoid Any under strict mypy.

from collections.abc import Iterable, Iterator

class NetworkXNoCycle(Exception): ...
class NetworkXError(Exception): ...

class DiGraph[NodeT]:
    def __init__(self, incoming_graph_data: object | None = None) -> None: ...
    def add_node(self, node: NodeT) -> None: ...
    def add_nodes_from(self, nodes: Iterable[NodeT]) -> None: ...
    def add_edge(self, u: NodeT, v: NodeT) -> None: ...
    def reverse(self) -> DiGraph[NodeT]: ...

def find_cycle[NodeT](g: DiGraph[NodeT]) -> list[tuple[NodeT, NodeT]]: ...
def topological_sort[NodeT](g: DiGraph[NodeT]) -> Iterator[NodeT]: ...
