# Generated by Django 6.0.4 on 2026-06-17 16:22

import django.contrib.auth.validators
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djangoapp.models.base
import djangoapp.models.public_ids
import uuid
from decimal import Decimal
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # pg_trgm must exist before the GIN trigram indexes on User below.
        TrigramExtension(),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='BooleanFieldModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('boolean_field', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharFieldModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('char_field', models.CharField(default='', max_length=100)),
                ('text_field', models.TextField(default='')),
                ('char_choice_field', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('optional_char_choice_field', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionalRowUpdatePermissionModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatetimeFieldModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime_field', models.DateTimeField(default=django.utils.timezone.now)),
                ('optional_datetime_field', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_field', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecimalFieldModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('decimal_field', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('optional_decimal_field', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileMarkedForDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FirstStuff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('char_field', models.CharField(default='foo', max_length=10)),
                ('text_field', models.TextField(blank=True, default='bar')),
                ('integer_field', models.IntegerField(default=1)),
                ('nullable_integer_field', models.IntegerField(default=10, null=True)),
                ('boolean_field', models.BooleanField(default=True)),
                ('decimal_field', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('datetime_field', models.DateTimeField(default=django.utils.timezone.now)),
                ('char_choice_field', models.CharField(choices=[('opt1', 'Option 1'), ('opt2', 'Option 2'), ('opt3', 'Option 3')], default='opt2', max_length=10)),
                ('int_choice_field', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncludeFirstTwo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int1', models.IntegerField(default=1)),
                ('int2', models.IntegerField(default=2)),
                ('int3', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerFieldModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('integer_field', models.IntegerField(default=0)),
                ('optional_integer_field', models.IntegerField(blank=True, default=0, null=True)),
                ('integer_choice_field', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Pending')], default=1)),
                ('optional_integer_choice_field', models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Pending')], default=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoreStuff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('char_field', models.CharField(default='char', max_length=10)),
                ('text_field', models.TextField(default='text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreventEditDeleteModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prevent_edit', models.BooleanField(default=False)),
                ('prevent_delete', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicIdSequenceTestModel1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicIdSequenceTestModel2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicIdUuid7TestModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_id', models.CharField(editable=False, max_length=36, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicIdUuid7TestModel2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True, validators=[djangoapp.models.public_ids.public_id_django_validator])),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicIdUuid7TestModel3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_id', models.UUIDField(editable=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('char_field', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchForFkTargetModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlotDemoModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('int1', models.IntegerField(default=0)),
                ('int2', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestFileUploadModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nullable_integer_field', models.IntegerField(default=10, null=True)),
                ('file_field', models.FileField(null=True, upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=djangoapp.models.base.BaseModel.generate_uuid7_id, editable=False, max_length=36, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('has_public_profile', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', djangoapp.models.base.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProxyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangoapp.user', models.Model),
            managers=[
                ('objects', djangoapp.models.base.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('public_id', models.CharField(max_length=255, unique=True, validators=[djangoapp.models.public_ids.public_id_django_validator])),
                ('content', models.TextField(blank=True, default='', max_length=50000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_commenting_enabled', models.BooleanField(default=True)),
                ('first_image', models.UUIDField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='djangoapp.articletag')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='djangoapp.article')),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-commented_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_public_id_copy', models.CharField(default='', max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('deleted', 'Deleted')], max_length=20)),
                ('_changes', models.JSONField(default=dict)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='djangoapp.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.UUIDField(default=uuid.uuid7, editable=False, help_text='Public id for the image', unique=True)),
                ('image', models.FileField(upload_to='uploads/article_images/')),
                ('size', models.PositiveBigIntegerField(default=0, help_text='Size of the uploaded image in bytes')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='djangoapp.article')),
            ],
        ),
        migrations.CreateModel(
            name='NotifyingFirstStuff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangoapp.firststuff',),
        ),
        migrations.CreateModel(
            name='ForeignKeyModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('category_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='djangoapp.categorymodel')),
                ('optional_category_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_items', to='djangoapp.categorymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='firststuff',
            name='ref_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='djangoapp.ref'),
        ),
        migrations.CreateModel(
            name='RowUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created_row', 'Created Row'), ('updated_row', 'Updated Row'), ('commented', 'Commented')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_values', models.JSONField(blank=True, default=list, null=True)),
                ('modelname', models.CharField(max_length=255)),
                ('row_pk', models.IntegerField()),
                ('row_public_id', models.CharField(default='', max_length=255)),
                ('comment_content', models.TextField(blank=True, default='', max_length=1000)),
                ('comment_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comment_edited_at', models.DateTimeField(blank=True, null=True)),
                ('comment_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RowUpdateUserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=255)),
                ('row_pk', models.IntegerField()),
                ('row_public_id', models.CharField(default='', max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchForFkDestinationModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_with_search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='destinations_with_search', to='djangoapp.searchforfktargetmodel')),
                ('fk_without_search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='destinations_without_search', to='djangoapp.searchforfktargetmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SerializerTestModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('char_field', models.CharField(blank=True, max_length=100)),
                ('char_choice_field', models.CharField(blank=True, choices=[('a', 'Option A'), ('b', 'Option B')], max_length=10)),
                ('char_with_default', models.CharField(default='default_value', max_length=50)),
                ('text_field', models.TextField(blank=True)),
                ('text_with_validator', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('integer_field', models.IntegerField(blank=True, null=True)),
                ('integer_choice_field', models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two')], null=True)),
                ('integer_with_default', models.IntegerField(default=42)),
                ('integer_with_callable_default', models.IntegerField(default=djangoapp.models.base._default_integer_callable)),
                ('boolean_field', models.BooleanField(default=False)),
                ('decimal_field', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('datetime_field', models.DateTimeField(blank=True, null=True)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fk_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='djangoapp.serializertestmodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name'], name='user_first_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='user_last_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='user_username_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddField(
            model_name='firststuff',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='djangoapp.proxyuser'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['article'], name='djangoapp_a_article_a40c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['commented_at'], name='djangoapp_a_comment_79b746_idx'),
        ),
        migrations.AddIndex(
            model_name='articlehistory',
            index=models.Index(fields=['article'], name='djangoapp_a_article_42c221_idx'),
        ),
        migrations.AddIndex(
            model_name='articlehistory',
            index=models.Index(fields=['time'], name='djangoapp_a_time_79b9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='rowupdate',
            index=models.Index(fields=['modelname', 'row_pk'], name='djangoapp_r_modelna_4d38ce_idx'),
        ),
        migrations.AddIndex(
            model_name='rowupdate',
            index=models.Index(fields=['modelname', 'row_public_id'], name='djangoapp_r_modelna_e40e35_idx'),
        ),
        migrations.AddIndex(
            model_name='rowupdate',
            index=models.Index(fields=['created_at'], name='djangoapp_r_created_e1aaad_idx'),
        ),
        migrations.AddIndex(
            model_name='rowupdateusernotification',
            index=models.Index(fields=['modelname', 'row_pk'], name='djangoapp_r_modelna_6758a5_idx'),
        ),
    ]
