# Generated by Django 6.0.4 on 2026-06-18 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user_public_id_copy', models.CharField(default='', max_length=36)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('deleted', 'Deleted')], max_length=20)),
                ('_changes', models.JSONField(default=dict)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['target_user'], name='djangoapp_u_target__911da5_idx'), models.Index(fields=['time'], name='djangoapp_u_time_c5b010_idx')],
            },
        ),
    ]
