# Generated by Django 6.0.4 on 2026-06-19 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
