# Generated by Django 6.0.4 on 2026-06-19 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_article_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_public_id', models.CharField(max_length=255)),
                ('comment_public_id', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-id'], name='djangoapp_a_user_id_5bbf67_idx')],
                'constraints': [models.UniqueConstraint(fields=('comment_public_id', 'user'), name='uniq_article_notif_per_comment_user')],
            },
        ),
    ]
