# Generated by Django 6.0.4 on 2026-06-24 19:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_article_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_id', models.CharField(editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllColumns',
            fields=[
                ('foomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoapp.foomodel')),
                ('char_field', models.CharField(default='foo', max_length=10)),
                ('char_choice_field', models.CharField(choices=[('opt1', 'Option 1'), ('opt2', 'Option 2'), ('opt3', 'Option 3')], default='opt2', max_length=10)),
                ('text_field', models.TextField(blank=True, default='bar')),
                ('integer_field', models.IntegerField(default=1)),
                ('boolean_field', models.BooleanField(default=True)),
                ('decimal_field', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('datetime_field', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
            bases=('djangoapp.foomodel',),
        ),
    ]
