from typing import Any

from django.test import TestCase

class InertiaTestCase(TestCase):
    # setUp-instanced attributes (ClientWithLastResponse / unittest mocks);
    # typed Any since their helper classes ship untyped.
    inertia: Any
    client: Any
    mock_inertia: Any
    mock_render: Any

    def assertComponentUsed(self, component: str) -> None: ...
    def component(self) -> str: ...
    def page(self) -> dict[str, Any]: ...
    def props(self) -> dict[str, Any]: ...
    def merge_props(self) -> dict[str, Any]: ...
    def deferred_props(self) -> dict[str, Any]: ...
    def assertHasExactProps(self, props: dict[str, Any]) -> None: ...
    def assertIncludesProps(self, props: dict[str, Any]) -> None: ...
    def assertHasExactTemplateData(self, data: dict[str, Any]) -> None: ...
    def assertIncludesTemplateData(self, data: dict[str, Any]) -> None: ...
    def template_data(self) -> dict[str, Any]: ...
