# Generated by Django 6.0.6 on 2026-06-28 10:22

import djangoapp.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_userhistory_user_user_first_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='public_id',
            field=models.CharField(default=djangoapp.models.base.generate_uuid7_id, editable=False, max_length=36, unique=True),
        ),
    ]
