# Generated by Django 6.0.6 on 2026-06-29 13:38

import django.core.validators
import django.db.models.deletion
import djangoapp.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_userhistory_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=djangoapp.models.base.generate_uuid7_id, editable=False, max_length=36, unique=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Only alphanumeric characters are allowed.')])),
                ('slug', models.CharField(editable=False, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Only alphanumeric characters are allowed.')])),
            ],
            options={
                'db_table': 'application_collection',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=djangoapp.models.base.generate_uuid7_id, editable=False, max_length=36, unique=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Only alphanumeric characters are allowed.')])),
                ('slug', models.CharField(editable=False, max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Only alphanumeric characters are allowed.')])),
                ('description', models.TextField(blank=True, default='')),
                ('application_collection', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='djangoapp.applicationcollection')),
            ],
            options={
                'db_table': 'application',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=djangoapp.models.base.generate_uuid7_id, editable=False, max_length=36, unique=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Only alphanumeric characters are allowed.')])),
                ('slug', models.CharField(editable=False, max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Only alphanumeric characters are allowed.')])),
                ('column_order', models.JSONField(default=list)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tables', to='djangoapp.application')),
            ],
            options={
                'db_table': 'application_table',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=djangoapp.models.base.generate_uuid7_id, editable=False, max_length=36, unique=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$', 'Column names must start with a letter and contain only letters and digits.')])),
                ('type', models.CharField(choices=[('char', 'Char'), ('text', 'Text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('decimal', 'Decimal'), ('datetime', 'Datetime'), ('user', 'User')], max_length=20)),
                ('char_choices', models.JSONField(blank=True, default=list)),
                ('text_default', models.TextField(blank=True, default='')),
                ('text_min_length', models.PositiveIntegerField(default=0)),
                ('text_max_length', models.PositiveIntegerField(default=1000)),
                ('nullable', models.BooleanField(default=False)),
                ('int_default', models.IntegerField(blank=True, null=True)),
                ('boolean_default', models.BooleanField(default=False)),
                ('decimal_default', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('decimal_max_digits', models.PositiveIntegerField(default=10)),
                ('decimal_places', models.PositiveIntegerField(default=2)),
                ('application_table', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='columns', to='djangoapp.applicationtable')),
            ],
            options={
                'db_table': 'application_table_column',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(models.F('application_collection'), models.F('slug'), name='application_collection_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(models.F('application_collection'), models.F('name'), name='application_collection_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='applicationtable',
            constraint=models.UniqueConstraint(models.F('application'), models.F('slug'), name='application_table_app_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='applicationtable',
            constraint=models.UniqueConstraint(models.F('application'), models.F('name'), name='application_table_app_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='applicationtablecolumn',
            constraint=models.UniqueConstraint(models.F('application_table'), models.F('name'), name='application_table_column_name_unique'),
        ),
    ]
