# Generated by Django 6.0.6 on 2026-06-29 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$', 'Must start with a letter and contain only letters and digits.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.CharField(editable=False, max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$', 'Must start with a letter and contain only letters and digits.')]),
        ),
        migrations.AlterField(
            model_name='applicationcollection',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$', 'Must start with a letter and contain only letters and digits.')]),
        ),
        migrations.AlterField(
            model_name='applicationcollection',
            name='slug',
            field=models.CharField(editable=False, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$', 'Must start with a letter and contain only letters and digits.')]),
        ),
        migrations.AlterField(
            model_name='applicationtable',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$', 'Must start with a letter and contain only letters and digits.')]),
        ),
        migrations.AlterField(
            model_name='applicationtable',
            name='slug',
            field=models.CharField(editable=False, max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$', 'Must start with a letter and contain only letters and digits.')]),
        ),
    ]
