# Generated by Django 6.0.6 on 2026-06-29 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_applications_leading_letter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='application_collection_slug_unique',
        ),
        migrations.RemoveConstraint(
            model_name='applicationtable',
            name='application_table_app_slug_unique',
        ),
        migrations.RemoveField(
            model_name='applicationcollection',
            name='slug',
        ),
        migrations.AlterField(
            model_name='applicationcollection',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$', 'Must start with a letter and contain only letters and digits.')]),
        ),
        migrations.RemoveField(
            model_name='application',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='applicationtable',
            name='slug',
        ),
    ]
