# Generated by Django 6.0.6 on 2026-07-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_physical_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtablecolumn',
            name='type',
            field=models.CharField(choices=[('char', 'char'), ('text', 'text'), ('integer', 'integer'), ('boolean', 'boolean'), ('decimal', 'decimal'), ('datetime', 'datetime'), ('user', 'user')], max_length=20),
        ),
    ]
