# Generated by Django 6.0.6 on 2026-07-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_application_static_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'apps_generation',
            },
        ),
    ]
