# Generated by Django 6.0.6 on 2026-07-25 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_executed_setups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]{3,}$', 'App names must be at least 4 chars, start with a letter, and contain only letters and digits.')]),
        ),
    ]
