# Generated by Django 6.0.6 on 2026-07-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0017_alter_application_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationtable',
            name='application_table_app_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='applicationtablecolumn',
            name='application_table_column_name_unique',
        ),
        migrations.DeleteModel(
            name='AppsGeneration',
        ),
        migrations.RemoveField(
            model_name='applicationtable',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationtablecolumn',
            name='application_table',
        ),
        migrations.RemoveField(
            model_name='applicationtablecolumn',
            name='fk_target_table',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ApplicationTable',
        ),
        migrations.DeleteModel(
            name='ApplicationTableColumn',
        ),
    ]
