# Generated by Django 6.0.6 on 2026-08-05 11:44

import django.db.models.deletion
import django.utils.timezone
import djangoapp.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0018_remove_apps_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModelUpdateLog',
            fields=[
                ('id', models.UUIDField(default=djangoapp.models.base.generate_uuid7_id, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.CharField(max_length=255)),
                ('model_pk', models.BigIntegerField()),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['model', 'model_pk'], name='djangoapp_b_model_598f7a_idx'), models.Index(fields=['performed_at'], name='djangoapp_b_perform_854525_idx')],
            },
        ),
    ]
