# Generated by Django 6.1 on 2026-09-13 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0021_rename_testloginkey_loginkey_and_more'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateTimeField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'expire_date'], name='djangoapp_u_user_id_6468eb_idx')],
            },
        ),
    ]
