# Generated by Django 6.1 on 2026-09-17 11:47

import django.db.models.deletion
import djangoapp.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0022_usersessionindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=djangoapp.models.base.generate_uuid7_id, editable=False, max_length=36, unique=True)),
                ('kind', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='djangoapp_n_recipie_d6a79d_idx')],
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
