# Generated by Django 6.1 on 2026-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0023_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('login', 'Login'), ('login_link', 'Login link'), ('logout_all', 'Logout all')], max_length=20),
        ),
    ]
