# Generated by Django 6.1 on 2026-09-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoapp", "0025_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="session_index",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_subscription",
                to="djangoapp.usersessionindex",
            ),
        ),
    ]
