# Generated by Django 6.1 on 2026-09-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoapp", "0026_pushsubscription_session_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-public_id"], name="djangoapp_n_recipie_531f33_idx"
            ),
        ),
    ]
