from typing import Any

from django.test import TestCase

class InertiaTestCase(TestCase):
    def assertComponentUsed(self, component: str) -> None: ...
    def component(self) -> str: ...
    def assertHasExactProps(self, props: dict[str, Any]) -> None: ...
    def assertIncludesProps(self, props: dict[str, Any]) -> None: ...
    def props(self) -> dict[str, Any]: ...
    def assertHasExactTemplateData(self, data: dict[str, Any]) -> None: ...
    def assertIncludesTemplateData(self, data: dict[str, Any]) -> None: ...
    def template_data(self) -> dict[str, Any]: ...
